# Generated by Django 5.2.7 on 2025-10-20 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('requires_serial', models.BooleanField(default=False)),
                ('is_bulk', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StockStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('is_warehouse', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_core.customer')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_core.region')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_core.technician')),
            ],
        ),
        migrations.CreateModel(
            name='StockTakeOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_management.stocklocation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockTakeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_management.itemtype')),
                ('stock_take', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory_management.stocktakeoverview')),
            ],
        ),
        migrations.CreateModel(
            name='StockTakeItemSerial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(db_index=True, max_length=64)),
                ('stock_take_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serials', to='inventory_management.stocktakeitem')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('stock_take_item', 'serial_number'), name='uniq_serial_per_line')],
            },
        ),
        migrations.AddConstraint(
            model_name='stocktakeitem',
            constraint=models.UniqueConstraint(fields=('stock_take', 'item_type'), name='uniq_item_per_take'),
        ),
    ]
