# Generated by Django 5.2.3 on 2025-06-15 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobCardCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_number', models.PositiveIntegerField(default=68746)),
            ],
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SupportAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('device_imei', models.CharField(max_length=30)),
                ('vehicle_reg', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('tampering', models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], help_text='Only applicable for inspection job types.', max_length=3, null=True)),
                ('accessories', models.ManyToManyField(blank=True, related_name='jobcards', to='jobcard_management.accessories')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobcards', to='backend_core.customer')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobcards', to='backend_core.region')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobcards', to='backend_core.technician')),
                ('job_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobcards', to='jobcard_management.jobtype')),
                ('support_agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobcards', to='jobcard_management.supportagent')),
            ],
        ),
    ]
